<?php
/**
 * Displays the necessary Sitewide Convert.com Experiments script after body start
 *
 * @package ConvertExperiments
 * @subpackage ConvertExperiments
 * @version 1.0.5
 * @author Robert Henderson
 */
?>
<?php $helper = Mage::helper('convert_experiments/data') ?>
<?php if($helper->isEnabled() == 1): ?>
<!-- begin Convert Experiments code-->
<script type="text/javascript" src="//cdn-3.convertexperiments.com/js/<?php echo str_replace("_", "-", $helper->getConvertProjectCode()) ?>.js"></script>
<!-- end Convert Experiments code -->
<?php endif; ?>